---

- name: Create base configuration from template for Hub Hosts
  template:
    src: hub-pan-baseline-{{ environment }}.j2
    dest: "{{ playbook_dir }}/hub-pan-baseline-{{ environment }}.xml"


- name: Upload base configuration for HUB Hosts
  panos_import:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    file: "{{ playbook_dir }}/hub-pan-baseline-{{ environment }}.xml"
    category: "configuration"
  register: result