---

#- name: Set Static Route
#  panos_op:
#    ip_address: "{{ mgmt_ip }}"
#    username: "{{ admin_username }}"
#    password: "{{ admin_password }}"
#    cmd: 'set network virtual-router default interface [ ethernet1/2 ] routing-table ip static-route default-route destination 0.0.0.0/0 nexthop ip-address 10.99.136.1'

- name: show system info
  panos_op:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    cmd: 'show system info'

- name: configure ethernet1/1
  panos_interface:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    if_name: "ethernet1/1"
    zone_name: "Untrusted"
    create_default_route: "yes"
    commit: False

- name: configure ethernet1/2
  panos_interface:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    if_name: "ethernet1/2"
    zone_name: "Trusted"
    create_default_route: "no"
    commit: False

- name: set dns and ntp
  panos_mgtconfig:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    dns_server_primary: "8.8.8.8"
    ntp_server_primary: "0.pool.ntp.org"
    ntp_server_secondary: "1.pool.ntp.org"
    timezone: "UTC"
    login_banner: "Secure environment"
    commit: True
