---

- name: wait for SSH (timeout 10min)
  wait_for: port=22 host="{{ mgmt_ip }}" search_regex=SSH timeout=600

- name: checking if device ready
  panos_check: 
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
  register: result
  until: not result|failed
  retries: 10
  delay: 10

- name: Create base configuration from template
  template:
    src: panos-baseline.xml.j2
    dest: "{{ playbook_dir }}/panos-baseline.xml"

- name: Upload base configuration
  panos_import:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    file: "{{ playbook_dir }}/panos-baseline.xml"
    category: "configuration"
  register: result

- name: load configuration
  panos_loadcfg:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    file: "{{ result.filename }}"
    commit: False

- name: show system info
  panos_op:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    cmd: 'show system info'

- name: commit
  panos_commit:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"

