---

- name: wait for SSH (timeout 10min)
  wait_for: port=22 host="{{ mgmt_ip }}" search_regex=SSH timeout=600

- name: checking if device ready
  panos_check: 
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
  register: result
  until: not result|failed
  retries: 10
  delay: 10

- name: Hub Config Deployment
  include_tasks: hub.yml
  when: paloname is match("hub*")

- name: Dmz Config Deployment
  include_tasks: dmz.yml
  when: paloname is match("dmz*")

- name: load configuration
  panos_loadcfg:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    file: "{{ result.filename }}"
    commit: False

- name: show system info
  panos_op:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    cmd: 'show system info'

- name: commit
  panos_commit:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"

