---

- name: set dns and ntp
  panos_mgtconfig:
    ip_address: "{{ mgmt_ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    dns_server_primary: "8.8.8.8"
    ntp_server_primary: "0.us.pool.ntp.org"
    ntp_server_secondary: "1.us.pool.ntp.org"
    timezone: "UTC/London"
    login_banner: "Secure environment"
    commit: True