pipeline {
    agent {
        dockerfile {
            dir 'pipelines'
        }
    }
    environment {
        
    }
    
    stages {
        stage('Terraform Plan') {        
            steps{ 
                ansiColor('xterm') {
                    sh  """   
                    terraform init -input=false
                    terraform plan -out tfplan -input=false
                    """
                } 
            }
       }   
    }

    post {
    success {
      mail to: "iromaniuk@advisor360.com", 
      subject:"SUCCESS: ${currentBuild.fullDisplayName}", 
      body: "The pipeline ${currentBuild.fullDisplayName} completed successfully."
    }
    failure {
      mail to: "iromaniuk@advisor360.com", 
      subject:"FAILURE: ${currentBuild.fullDisplayName}", 
      body: "Something is wrong with ${env.BUILD_URL} #${env.BUILD_NUMBER} #${env.JOB_NAME}"
    }
    
  }
}    